[package]
name = "git-in-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
flate2 = "1.0.28"
hex = "0.4.3"
rust-crypto = "0.2.36"
sha1 = "0.10.6"
walkdir = "2"
